# Generated by Django 5.2.4 on 2025-07-25 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costumerportal', '0006_product_is_active'),
        ('productmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Phone', models.CharField(max_length=10)),
                ('order_type', models.CharField(max_length=1)),
                ('delivery_type', models.CharField(max_length=1)),
                ('Address', models.CharField(max_length=255)),
                ('Size', models.CharField(blank=True, max_length=60, null=True)),
                ('Color', models.CharField(blank=True, max_length=60, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='costumerportal.product')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='productmanager.wilayainfo')),
            ],
        ),
    ]
