# Generated by Django 5.2.4 on 2025-07-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpilot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='IDwilaya',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='wilaya',
            field=models.CharField(max_length=60),
        ),
    ]
