# Generated by Django 5.2.4 on 2025-07-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpilot', '0002_order_idwilaya_alter_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='IDwilaya',
            field=models.CharField(max_length=2),
        ),
    ]
