# Generated by Django 5.2.4 on 2025-07-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpilot', '0004_order_total_alter_order_delivery_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
