# Generated by Django 5.2.4 on 2025-07-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumerportal', '0003_color_size_delete_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='color/'),
        ),
    ]
