# Generated by Django 5.2.4 on 2025-07-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumerportal', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
